# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
  - $HOME/usr/local

r_github_packages:
  - jimhester/covr

env:
  global:
    - secure: U5L4JHPa5/mpcDjL60XZVDXtT/nQe4lyhCG6pIj7dF8N6iLRO/vh0ChPxZsBhunKaNMnu59MEqn9nvp09kodV7DzW1nNV+UVi2ZtXpAFejHOK6T4d31vGShCnoM5BkTeMp7exX8yfKWw3Zw0JY47sHTLFihYbwUFqsus0aqT0hIK
    
before_install:
  - bash build-cmtk.sh

before_script:
  - export PATH=$PATH:$HOME/usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
after_success:
  - Rscript -e 'devtools::install();nat::cmtk.mat2dof(version=TRUE)'
  - Rscript -e 'library(covr);coveralls(exlusions="R/zzz.R")'
  - bash travisbuildchildren.sh
